"""Classify a file under Lib/ as 'tests', 'generated' or 'stdlib'.

The rules are described in PROTOCOL.md. Tests win over generated: a generated
file inside a test tree is test material.

    uv run harness/classify.py work/Python-3.14.0/Lib   # list what counts as generated
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

TEST_PARTS = frozenset({'test', 'tests', 'idle_test', 'testdata', 'test_data', 'tokenizedata'})

# Markers that CPython's generated files actually carry (the survey is in
# PROTOCOL.md): a comment line that *starts* with the marker, a "this file is
# generated" sentence, gencodec's codec docstring, or a do-not-edit notice.
# Prose such as "can be generated by passing" (ast.py), "tables generated by
# pgen" (pgen2/parse.py) or "streams generated with Python 2"
# (_compat_pickle.py) is deliberately not matched.
GENERATED_RX = re.compile(
    r"(?im)^\s*#\s*(?:this file (?:is|was) )?(?:auto-?generated|automatically generated|generated (?:by|from))"
    r"|this file (?:is|was) (?:automatically |auto-?)?generated"
    r"|do not edit|don't muck it up"
    r"|python character mapping codec"   # every charmap codec is a gencodec table or derived from one
)
# Table dumps that carry no marker at all.
GENERATED_EXPLICIT = frozenset({'msilib/schema.py', 'msilib/sequence.py'})
HEAD_LINES = 15
CATEGORIES = ('stdlib', 'tests', 'generated')


def head_text(data: bytes) -> str:
    return b'\n'.join(data.splitlines()[:HEAD_LINES]).decode('utf-8', 'replace')


def is_test(rel: str) -> bool:
    return any(part in TEST_PARTS for part in rel.split('/')[:-1])


def is_generated(rel: str, head: str) -> bool:
    return rel in GENERATED_EXPLICIT or GENERATED_RX.search(head) is not None


def category(rel: str, head: str) -> str:
    if is_test(rel):
        return 'tests'
    if is_generated(rel, head):
        return 'generated'
    return 'stdlib'


if __name__ == '__main__':
    lib = Path(sys.argv[1])
    for p in sorted(lib.rglob('*.py')):
        rel = p.relative_to(lib).as_posix()
        if not is_test(rel) and is_generated(rel, head_text(p.read_bytes())):
            print(rel)
